# Unique identifier of the project
sonar.projectKey=Isabela-CP_PlanejaAi
# Name of the project
sonar.projectName=Planeja.AI
# Organization (for SonarCloud)
sonar.organization=isabela-cp

# Path to the source directories (relative to project root)
sonar.sources=planeja_ai/lib,planeja_ai/backend/src

# Path to the test directories
sonar.tests=planeja_ai/test,planeja_ai/backend/tests

# Source file encoding
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/build/**,**/android/**,**/ios/**,**/macos/**,**/windows/**,**/linux/**,**/web/**,**/*.g.dart,**/*.freezed.dart,**/pubspec.yaml,**/pubspec.lock,**/venv/**,**/.venv/**,**/assets/**,**/*.md,**/test_conn.dart,**/test_multipart.dart,**/dummy.py,**/coverage/**,**/Dockerfile,**/Makefile,**/docker-compose.yml,**/*.yaml

# Coverage paths
sonar.dart.lcov.reportPath=planeja_ai/coverage/lcov.info
sonar.python.coverage.reportPaths=planeja_ai/backend/coverage.xml

# Exclusions from coverage (Frontend source code and backend endpoints/models/config)
sonar.coverage.exclusions=**/lib/**,**/backend/src/app/controllers/**,**/backend/src/app/models/**,**/backend/src/config/app.py

# Exclusions from duplication checks (CPD)
sonar.cpd.exclusions=**/lib/**,**/backend/src/app/controllers/**,**/backend/src/app/models/**,**/backend/src/config/app.py

sonar.issue.ignore.multicriteria=e1,e2,e3
sonar.issue.ignore.multicriteria.e1.ruleKey=*
sonar.issue.ignore.multicriteria.e1.resourceKey=**/test/**/*,**/tests/**/*
sonar.issue.ignore.multicriteria.e2.ruleKey=*
sonar.issue.ignore.multicriteria.e2.resourceKey=**/backend/src/config/**/*
sonar.issue.ignore.multicriteria.e3.ruleKey=*
sonar.issue.ignore.multicriteria.e3.resourceKey=**/lib/**/*